# Generated by Django 5.1 on 2025-10-16 11:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyfees', '0001_initial'),
        ('student', '0003_alter_term_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familyfeerecord',
            options={'ordering': ['-date_created'], 'verbose_name': 'Family Fee Record', 'verbose_name_plural': 'Family Fee Records'},
        ),
        migrations.AddField(
            model_name='familyfeerecord',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familyfeerecord',
            name='is_fully_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='familyfeerecord',
            unique_together={('family', 'term', 'academic_year')},
        ),
    ]
