# Generated by Django 5.1 on 2025-10-19 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familyfees', '0002_alter_familyfeerecord_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': 'Family', 'verbose_name_plural': 'Families'},
        ),
    ]
