# Generated by Django 5.1 on 2025-11-24 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familyfees', '0003_alter_family_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['-id'], 'verbose_name': 'Family', 'verbose_name_plural': 'Families'},
        ),
        migrations.AlterModelOptions(
            name='familyfeerecord',
            options={'ordering': ['-id'], 'verbose_name': 'Family Fee Record', 'verbose_name_plural': 'Family Fee Records'},
        ),
        migrations.AlterModelOptions(
            name='familypayment',
            options={'ordering': ['-id'], 'verbose_name': 'Family Payment', 'verbose_name_plural': 'Family Payments'},
        ),
    ]
