# Generated by Django 5.1 on 2025-10-11 01:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('student', '0008_alter_studentprofile_has_allergies_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff',
            new_name='StaffProfile',
        ),
    ]
