# Generated by Django 5.1 on 2025-10-11 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='reference',
        ),
    ]
