# Generated by Django 5.1 on 2025-10-13 16:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_remove_payment_reference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentfeerecord',
            options={'ordering': ['-date_created'], 'verbose_name': 'Student Fee Record', 'verbose_name_plural': 'Student Fee Records'},
        ),
        migrations.AddField(
            model_name='studentfeerecord',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
