# Generated by Django 5.1 on 2025-10-13 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_alter_studentfeerecord_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentfeerecord',
            options={'ordering': ['-date_created'], 'verbose_name': 'Student Fee Record', 'verbose_name_plural': 'Student Fee Records'},
        ),
    ]
