# Generated by Django 5.1 on 2025-10-19 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_alter_studentfeerecord_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together=set(),
        ),
    ]
