# Generated by Django 5.1 on 2025-11-24 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_alter_feestructure_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-id'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
    ]
