# Generated by Django 5.1 on 2025-11-24 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0007_alter_payment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentfeerecord',
            options={'ordering': ['-id'], 'verbose_name': 'Student Fee Record', 'verbose_name_plural': 'Student Fee Records'},
        ),
    ]
