# Generated by Django 5.1 on 2025-12-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0008_alter_studentfeerecord_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='is_discounted',
            field=models.BooleanField(default=False),
        ),
    ]
