# Generated by Django 5.1 on 2025-12-08 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0009_feestructure_is_discounted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feestructure',
            old_name='is_discounted',
            new_name='for_discounted_student',
        ),
    ]
