# Generated by Django 5.1 on 2025-12-08 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0010_rename_is_discounted_feestructure_for_discounted_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feestructure',
            old_name='for_discounted_student',
            new_name='is_discounted',
        ),
    ]
