# Generated by Django 5.1 on 2025-12-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0011_rename_for_discounted_student_feestructure_is_discounted'),
        ('student', '0007_rename_is_dicounted_student_studentprofile_is_discounted_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='discounted_student_ids',
            field=models.ManyToManyField(blank=True, to='student.studentprofile'),
        ),
    ]
