# Generated by Django 5.1 on 2025-10-11 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GradeClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('creche', 'creche'), ('nursery 1', 'nursery 1'), ('nursery 2', 'nursery 2'), ('kg 1', 'kg 1'), ('kg 2', 'kg 2'), ('class 1', 'class 1'), ('class 2', 'class 2'), ('class 3', 'class 3'), ('class 4', 'class 4'), ('class 5', 'class 5'), ('class 6', 'class 6'), ('jhs 1', 'jhs 1'), ('jhs 2', 'jhs 2'), ('jhs 3', 'jhs 3')], max_length=40, verbose_name='Class')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staffprofile', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_school_attended', models.CharField(blank=True, max_length=255, null=True)),
                ('class_seeking_admission_to', models.CharField(blank=True, choices=[('creche', 'creche'), ('nursery 1', 'nursery 1'), ('nursery 2', 'nursery 2'), ('kg 1', 'kg 1'), ('kg 2', 'kg 2'), ('class 1', 'class 1'), ('class 2', 'class 2'), ('class 3', 'class 3'), ('class 4', 'class 4'), ('class 5', 'class 5'), ('class 6', 'class 6'), ('jhs 1', 'jhs 1'), ('jhs 2', 'jhs 2'), ('jhs 3', 'jhs 3')], max_length=20, null=True)),
                ('is_immunized', models.CharField(blank=True, max_length=200, null=True)),
                ('has_allergies', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=10, null=True)),
                ('allergic_foods', models.CharField(blank=True, max_length=300, null=True)),
                ('has_peculiar_health_issues', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=10, null=True)),
                ('health_issues', models.CharField(blank=True, max_length=150, null=True)),
                ('other_related_info', models.TextField(blank=True, null=True)),
                ('name_of_father', models.CharField(blank=True, max_length=100, null=True)),
                ('name_of_mother', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation_of_father', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation_of_mother', models.CharField(blank=True, max_length=100, null=True)),
                ('nationality_of_father', models.CharField(blank=True, max_length=100, null=True)),
                ('nationality_of_mother', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_of_father', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_of_mother', models.CharField(blank=True, max_length=100, null=True)),
                ('house_number', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentTermRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.IntegerField(default=0)),
                ('comments', models.TextField(blank=True, null=True)),
                ('grade_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.gradeclass', verbose_name='Class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubjectRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_score', models.FloatField(default=0)),
                ('exam_score', models.FloatField(default=0)),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
                ('student_term_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='student.studenttermrecord')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1st Term', '1st Term'), ('2nd Term', '2nd Term'), ('3rd Term', '3rd Term')], max_length=20)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.academicyear')),
            ],
        ),
        migrations.AddField(
            model_name='studenttermrecord',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.term'),
        ),
        migrations.AlterUniqueTogether(
            name='studenttermrecord',
            unique_together={('student', 'term')},
        ),
    ]
