# Generated by Django 5.1 on 2025-09-20 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_school_attended', models.CharField(max_length=255)),
                ('class_seeking_admission_to', models.CharField(choices=[('creche', 'creche'), ('nursery 1', 'nursery 1'), ('nursery 2', 'nursery 2'), ('kg 1', 'kg 1'), ('kg 2', 'kg 2'), ('class 1', 'class 1'), ('class 2', 'class 2'), ('class 3', 'class 3'), ('class 4', 'class 4'), ('class 5', 'class 5'), ('class 6', 'class 6')], max_length=20)),
                ('has_allergies', models.BooleanField(default=False)),
                ('allergic_foods', models.CharField(max_length=300)),
                ('has_peculiar_health_issues', models.BooleanField(default=False)),
                ('health_issues', models.CharField(max_length=150)),
                ('other_related_info', models.TextField()),
                ('name_of_father', models.CharField(max_length=100)),
                ('name_of_mother', models.CharField(max_length=100)),
                ('occupation_of_father', models.CharField(max_length=100)),
                ('occupation_of_mother', models.CharField(max_length=100)),
                ('nationality_of_father', models.CharField(max_length=100)),
                ('nationality_of_mother', models.CharField(max_length=100)),
                ('contact_of_father', models.CharField(max_length=100)),
                ('contact_of_mother', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
