# Generated by Django 5.1 on 2025-10-14 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentprofile_current_class'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('name', 'academic_year')},
        ),
    ]
