# Generated by Django 5.1 on 2025-09-21 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_academicyear_subject_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradeclass',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
    ]
