# Generated by Django 5.1 on 2025-11-24 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_term_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradeclass',
            options={'ordering': ['-id'], 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['-id']},
        ),
    ]
