# Generated by Django 5.1 on 2025-10-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_gradeclass_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_immunized',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
