# Generated by Django 5.1 on 2025-12-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_gradeclass_options_alter_term_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeclass',
            name='name',
            field=models.CharField(choices=[('Creche', 'Creche'), ('Nursery 1A', 'Nursery 1A'), ('Nursery 1B', 'Nursery 1B'), ('Nursery 2A', 'Nursery 2A'), ('Nursery 2B', 'Nursery 2B'), ('KG 1A', 'KG 1A'), ('KG 1B', 'KG 1B'), ('KG 2A', 'KG 2A'), ('KG 2B', 'KG 2B'), ('Basic 1A', 'Basic 1A'), ('Basic 1B', 'Basic 1B'), ('Basic 2A', 'Basic 2A'), ('Basic 2B', 'Basic 2B'), ('Basic 3A', 'Basic 3A'), ('Basic 3B', 'Basic 3B'), ('Basic 4A', 'Basic 4A'), ('Basic 4B', 'Basic 4B'), ('Basic 5A', 'Basic 5A'), ('Basic 5B', 'Basic 5B'), ('Basic 6A', 'Basic 6A'), ('Basic 6B', 'Basic 6B'), ('Basic 7A', 'Basic 7A'), ('Basic 7B', 'Basic 7B'), ('Basic 8', 'Basic 8'), ('Basic 9', 'Basic 9')], max_length=40, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='current_class',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Creche'), (2, 'Nursery 1A'), (3, 'Nursery 1B'), (4, 'Nursery 2A'), (5, 'Nursery 2B'), (6, 'KG 1A'), (7, 'KG 1B'), (8, 'KG 2A'), (9, 'KG 2B'), (10, 'Basic 1A'), (11, 'Basic 1B'), (12, 'Basic 2A'), (13, 'Basic 2B'), (14, 'Basic 3A'), (15, 'Basic 3B'), (16, 'Basic 4A'), (17, 'Basic 4B'), (18, 'Basic 5A'), (19, 'Basic 5B'), (20, 'Basic 6A'), (21, 'Basic 6B'), (22, 'Basic 7A'), (23, 'Basic 7B'), (24, 'Basic 8'), (25, 'Basic 9')], default=1),
        ),
    ]
