# Generated by Django 5.1 on 2025-12-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_gradeclass_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_dicounted_student',
            field=models.BooleanField(default=False),
        ),
    ]
