# Generated by Django 5.1 on 2025-10-11 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_studentprofile_is_immunized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='class_seeking_admission_to',
            field=models.CharField(blank=True, choices=[('creche', 'creche'), ('nursery 1', 'nursery 1'), ('nursery 2', 'nursery 2'), ('kg 1', 'kg 1'), ('kg 2', 'kg 2'), ('class 1', 'class 1'), ('class 2', 'class 2'), ('class 3', 'class 3'), ('class 4', 'class 4'), ('class 5', 'class 5'), ('class 6', 'class 6'), ('jhs 1', 'jhs 1'), ('jhs 2', 'jhs 2'), ('jhs 3', 'jhs 3')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='contact_of_father',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='contact_of_mother',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='last_school_attended',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='name_of_father',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='name_of_mother',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='nationality_of_father',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='nationality_of_mother',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
