# Generated by Django 5.1 on 2025-10-11 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_studentprofile_class_seeking_admission_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='other_related_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
