# Generated by Django 5.1 on 2025-12-08 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_studentprofile_is_dicounted_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='is_dicounted_student',
            new_name='is_discounted_student',
        ),
    ]
