# Generated by Django 5.1 on 2025-10-11 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_studentprofile_other_related_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='has_allergies',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='has_peculiar_health_issues',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=10, null=True),
        ),
    ]
